<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>disable</Nullable>
    <AssemblyName>PorticoRti1516e.Native.TestFederate</AssemblyName>
    <RootNamespace>PorticoRti1516e.Native.TestFederate</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PorticoRti1516e.Native\PorticoRti1516e.Native.vcxproj" />
    <ProjectReference Include="..\PorticoRti1516e.Federate.Contracts\PorticoRti1516e.Federate.Contracts.csproj" />
  </ItemGroup>

</Project>
